"""Source-led replacement geometry for the four adjacent Railyards buildings.

This module owns only the medical main/wing, left-field pavilion, north
entertainment hall, and rounded centerfield restaurant.  It writes geometry to
the caller's MeshBatch and leaves legacy-object visibility and flushing to the
integrator.  Heights and roof depths are visual priors, not surveyed facts.
"""

import json
import math
from pathlib import Path

import bpy
from mathutils import Vector

from r2_geometry import text, instances
from r3_reference_projection import source_to_plane
from r3_medical import build_medical
from r3_restaurant import build_restaurant


OUT = Path(__file__).resolve().parent
with (OUT / 'adjacent-building-spec.json').open(encoding='utf-8') as _handle:
    ADJACENT_SPEC = json.load(_handle)

GROUP = 'Adjacent buildings'


def _xy(point):
    return (float(point[0]), float(point[1]))


def _area(footprint):
    return sum(a[0] * b[1] - b[0] * a[1]
               for a, b in zip(footprint, footprint[1:] + footprint[:1])) * 0.5


def _inset(footprint, fraction):
    cx = sum(point[0] for point in footprint) / len(footprint)
    cy = sum(point[1] for point in footprint) / len(footprint)
    return [(cx + (x - cx) * fraction, cy + (y - cy) * fraction)
            for x, y in footprint]


def _edge(footprint, index):
    a = Vector((*footprint[index], 0))
    b = Vector((*footprint[(index + 1) % len(footprint)], 0))
    tangent = (b - a).normalized()
    # For CCW footprints, the right-hand normal points outward.
    outward = Vector((tangent.y, -tangent.x, 0))
    if _area(footprint) < 0:
        outward.negate()
    return a, b, tangent, outward, (b - a).length, math.atan2(tangent.y, tangent.x)


def _roof_and_parapet(batch, name, footprint, roof_z, material='roof',
                      parapet_height=0.55, overhang=0.0):
    """Add a roof slab and a readable perimeter parapet."""
    if overhang:
        footprint = _inset(footprint, 1.0 + overhang / max(1.0, max(
            (Vector((*footprint[(i + 1) % len(footprint)], 0)) -
             Vector((*footprint[i], 0))).length for i in range(len(footprint)))))
    batch.prism(name, material, footprint, roof_z, roof_z + 0.18)
    for i in range(len(footprint)):
        a, b, _tangent, outward, length, angle = _edge(footprint, i)
        center = (a + b) * 0.5 + outward * 0.12
        center.z = roof_z + parapet_height * 0.5
        batch.box(name, 'stone', tuple(center), (length + 0.2, 0.28,
                                                  parapet_height), angle)


def _facade(batch, name, footprint, base_z, roof_z, spacing,
            window_material='glass_lit', pier_material='stone',
            window_fraction=0.68, level_height=4.2,
            mass_material='brick', window_height_fraction=.82):
    """Create a solid building mass with independently legible facade bays."""
    # The windows and piers are placed just outside this prism.  Keeping the
    # wall continuous behind the curtain wall avoids the floating luminous
    # grid that results when facade details are generated by themselves.
    batch.prism(name, mass_material, footprint, base_z, roof_z)
    floors = max(1, round((roof_z - base_z) / level_height))
    floor_height = (roof_z - base_z) / floors
    for edge_index in range(len(footprint)):
        a, b, tangent, outward, length, angle = _edge(footprint, edge_index)
        count = max(1, round(length / spacing))
        bay = length / count
        for floor in range(floors):
            z = base_z + floor * floor_height + floor_height * 0.53
            for bay_index in range(count):
                center = a.lerp(b, (bay_index + 0.5) / count)
                center += outward * 0.14
                center.z = z
                selected=window_material
                if window_material=='glass_lit':
                    selected=['glass_dim','glass_mid','glass_lit','glass_mid','glass_dim'][(bay_index+floor*3+edge_index)%5]
                batch.box(name, selected, tuple(center),
                          (bay * window_fraction, 0.12,
                           floor_height * window_height_fraction), angle)
                if window_fraction>.5:
                    # Source-visible tall glazing has finer transoms within
                    # the primary architectural bays; frame depth is inferred.
                    for f in [-1/6,1/6]:
                        q=center+outward*.09;q.z+=floor_height*window_height_fraction*f
                        batch.box(name+' glazing frames','metal',q,(bay*window_fraction,.10,.055),angle)
                    if bay*window_fraction>3:
                        q=center+outward*.09
                        batch.box(name+' glazing frames','metal',q,(.055,.10,floor_height*window_height_fraction),angle)
                # Narrow piers retain the source's vertical cadence at a
                # distance and keep the mass from reading as a tiled cube.
                pier = a.lerp(b, bay_index / count) + outward * 0.20
                pier.z = z
                batch.box(name, pier_material, tuple(pier),
                          (0.18, 0.25, floor_height * 0.88), angle)
            sill = (a + b) * 0.5 + outward * 0.21
            sill.z = base_z + floor * floor_height + 0.35
            batch.box(name, 'stone', tuple(sill),
                      (length + 0.15, 0.18, 0.16), angle)
        cap = (a + b) * 0.5 + outward * 0.20
        cap.z = roof_z - 0.28
        batch.box(name, 'stone', tuple(cap), (length + 0.25, 0.35, 0.35), angle)


def _roof_terrace(batch, name, footprint, roof_z, inset_fraction=0.78,
                  lawn_material='lawn'):
    terrace = _inset(footprint, inset_fraction)
    batch.prism(name, lawn_material, terrace, roof_z + 0.20, roof_z + 0.32)
    for index in range(len(terrace)):
        a, b, _tangent, outward, length, angle = _edge(terrace, index)
        center = (a + b) * 0.5 + outward * 0.08
        center.z = roof_z + 0.55
        batch.box(name, 'metal', tuple(center), (length, 0.10, 0.85), angle)


def _gable_roof(batch, name, footprint, eave_z, ridge_z):
    """Add a simple long-axis gable roof to a source-visible pavilion."""
    xs = [point[0] for point in footprint]
    ys = [point[1] for point in footprint]
    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    xm = (x0 + x1) * 0.5
    vertices = [
        (x0, y0, eave_z), (x1, y0, eave_z), (xm, y0, ridge_z),
        (x0, y1, eave_z), (x1, y1, eave_z), (xm, y1, ridge_z)
    ]
    faces = [
        (0, 1, 2), (3, 5, 4), (0, 3, 4, 1),
        (0, 2, 5, 3), (1, 4, 5, 2)
    ]
    batch.add(name, 'roof', vertices, faces)


def _find_building(spec, name):
    for building in spec.get('buildings', []):
        if building.get('name') == name:
            return [_xy(point) for point in building['footprint']]
    raise KeyError(f'Missing adjacent-building footprint: {name}')


def _medical(batch, scene, spec, materials):
    main = _find_building(spec, 'Medical main')
    wing = _find_building(spec, 'Medical wing')
    _facade(batch, 'Medical main', main, 8, 27, 2.8,
            window_material='glass', pier_material='aluminum',
            window_fraction=0.72, mass_material='brick_dark')
    _roof_and_parapet(batch, 'Medical main', main, 27, 'roof', 0.65)
    _roof_terrace(batch, 'Medical main', main, 27, 0.75)
    # The source has a finer, lower wing stepping away from the sign bar.
    _facade(batch, 'Medical wing', wing, 8, 23, 3.2,
            window_material='glass_lit', pier_material='aluminum',
            window_fraction=0.70, mass_material='brick_dark')
    _roof_and_parapet(batch, 'Medical wing', wing, 23, 'roof', 0.55)
    _roof_terrace(batch, 'Medical wing', wing, 23, 0.72)
    # The source's main bar terminates in a visibly lighter glazed volume.
    a, b, _tangent, outward, length, angle = _edge(main, 2)
    end = a.lerp(b, 0.55) + outward * 0.55
    end.z = 21.0
    batch.box('Medical main', 'glass_lit', tuple(end),
              (min(length * 0.22, 17.0), 3.2, 8.2), angle)

    # Edge 2 is the broad east/south-facing face visible from the north
    # camera.  Negative-winding footprints need a half-turn so font normals
    # face the computed outward direction.
    sign_edge = 2
    a, b, tangent, outward, length, angle = _edge(main, sign_edge)
    sign_center = a.lerp(b, 0.52) + outward * 0.31
    sign_center.z = 23.85
    sign_angle = angle + (math.pi if _area(main) < 0 else 0.0)
    text(scene, batch.collection(GROUP), 'Northwestern Medicine sign',
         'Northwestern\nMedicine', tuple(sign_center), 2.15,
         materials['purple_sign'], (math.pi / 2, 0, sign_angle))
    horizontal=Vector((math.cos(sign_angle),math.sin(sign_angle),0))
    brand=sign_center-horizontal*15;brand.z-=1.3
    text(scene,batch.collection(GROUP),'Northwestern monogram','NM',brand,5.3,
         materials['purple_sign'],(math.pi/2,0,sign_angle))
    # A restrained roof mechanical screen gives the main bar a stepped top
    # without inventing a tower absent from the source image.
    center = Vector((sum(point[0] for point in main) / len(main),
                     sum(point[1] for point in main) / len(main), 28.25))
    batch.box('Medical main', 'aluminum', tuple(center), (8.5, 4.5, 1.1))


def _left_field_pavilion(batch, scene, spec):
    # Two independently visible front corners recover cornice height 33.1 m
    # from ground z8 with the calibrated north camera. The back-left corner
    # is occluded and remains a parallelogram reconstruction assumption.
    camera=bpy.data.objects['R2_north']
    pixels=[(869,526),(977,577),(1190,459),(1082,410)]
    footprint=[source_to_plane(scene,camera,p,(1944,1294),33.1)[:2] for p in pixels]
    if _area(footprint)<0:footprint.reverse()
    _facade(batch,'Left field pavilion',footprint,8,33.1,3.7,
            window_material='glass_mid',pier_material='brick_light',
            window_fraction=.55,level_height=5.8)
    _roof_and_parapet(batch,'Left field pavilion',footprint,33.1,'stone',.6)
    # Recover the two source-visible dark roof footprints separately from
    # the full exterior cornice. These heights are inferred, unlike the
    # strongly constrained front cornice and its visible ground corners.
    roofs=[([(936,457),(1067,506),(1005,533),(895,512)],35.5),
           ([(1040,400),(1110,426),(1080,470),(1050,491),(958,466)],39.5),
           ([(1024,374),(1176,417),(1090,459),(994,415)],44.0)]
    for points,height in roofs:
        top=[source_to_plane(scene,camera,p,(1944,1294),height) for p in points]
        batch.add('Left field roof canopies','roof',top,[tuple(range(len(top)))])
        for a,b in zip(top,top[1:]+top[:1]):
            batch.quad('Left field roof fascia','metal',[a,b,(b[0],b[1],b[2]-.35),(a[0],a[1],a[2]-.35)])
        for p in top:
            batch.cylinder('Left field canopy supports','metal',(p[0],p[1],33.3),p,.10,sides=8)
    terrace=[source_to_plane(scene,camera,p,(1944,1294),33.4) for p in [(899,525),(969,551),(1006,534),(934,509)]]
    for i in range(10):
        c=Vector(terrace[0]).lerp(Vector(terrace[1]),(i+.5)/10)
        batch.cylinder('Left field terrace dining','white',(c.x,c.y,34.05),(c.x,c.y,34.14),.65,sides=12)
        batch.cylinder('Left field terrace dining','metal',c,(c.x,c.y,34.05),.07,sides=8)
    # A glazed bridge hall joins the two source-defined adjacent buildings.
    link_pixels=[(1110,510),(1250,554),(1245,585),(1103,541)]
    link=[source_to_plane(scene,camera,p,(1944,1294),28.5)[:2] for p in link_pixels]
    if _area(link)<0:link.reverse()
    _facade(batch,'Pavilion hall connector',link,14.1,28.5,3.1,
            window_material='glass_lit',pier_material='metal',window_fraction=.88)
    _roof_and_parapet(batch,'Pavilion hall connector',link,28.5,'roof',.20)


def _north_entertainment_hall(batch, scene, spec):
    camera=bpy.data.objects['R2_north']
    # Two visible vertical corners imply ~41-43 m roof with the park at
    # z14.1. Source-image perspective residual is 1-2 m; hidden depth inferred.
    roof_z=41.8
    pixels=[(1252,512),(1774,688),(1714,821),(1210,611)]
    footprint=[source_to_plane(scene,camera,p,(1944,1294),roof_z)[:2]for p in pixels]
    if _area(footprint)<0:footprint.reverse()
    _facade(batch,'North entertainment hall',footprint,14.1,roof_z,5.8,
            window_material='glass_mid',pier_material='brick_light',
            window_fraction=.90,level_height=6.8,mass_material='brick')
    _roof_and_parapet(batch,'North entertainment hall',footprint,roof_z,'stone',.7)
    # Broad continuous glazing, deep full-height brick piers and fine
    # intermediate metal mullions on the source-visible park facade.
    edge=max(range(len(footprint)),key=lambda i:(_edge(footprint,i)[3].x))
    a,b,tangent,outward,length,angle=_edge(footprint,edge)
    for i in range(1,9):
        c=a.lerp(b,i/9)+outward*.4;c.z=27.7
        batch.box('Hall brick piers','brick_light',c,(1.4,.8,27.2),angle)
    for i in range(1,36):
        c=a.lerp(b,i/36)+outward*.31;c.z=27.7
        batch.box('Hall glazing mullions','metal',c,(.10,.14,26.8),angle)
    def at(pixel,z=roof_z+.3):
        return Vector(source_to_plane(scene,camera,pixel,(1944,1294),z))
    canopy=[at(p,45.0) for p in [(1252,512),(1491,578),(1409,642),(1210,582)]]
    batch.add('Hall rooftop dining canopy','roof',canopy,[(0,1,2,3)])
    for c in canopy:
        batch.cylinder('Hall rooftop dining canopy','metal',(c.x,c.y,roof_z),(c.x,c.y,45),.13,sides=8)
    # Source garden is concentrated at the north/right end, with three
    # shaded terrace pockets along the public edge, not one lawn rectangle.
    garden=[at(p)for p in [(1510,611),(1735,688),(1707,753),(1472,674)]]
    batch.add('Hall roof garden','lawn',garden,[(0,1,2,3)])
    for k,pixel in enumerate([(1465,665),(1557,700),(1660,747)]):
        c=at(pixel)
        for j in range(13):
            q=c+tangent*(j-6)*.55;q.z=44.2
            batch.box('Hall terrace pergolas','metal',q,(.18,5.0,.18),angle)
        for dx in [-3.3,3.3]:
            for dy in [-2.5,2.5]:
                q=c+tangent*dx+outward*dy
                batch.cylinder('Hall terrace pergolas','metal',(q.x,q.y,roof_z),(q.x,q.y,44.2),.08,sides=6)
    tree=bpy.data.objects.get('D2_Broadleaf tree 0')
    if tree:
        points=[at(p) for p in [(1521,627),(1591,650),(1675,688),(1716,710)]]
        instances(scene,batch.collection(GROUP),'Hall roof trees',tree,points,
                  [(0,0,i*.7)for i in range(4)],[(.55,.55,.65)]*4)
    walker=bpy.data.objects.get('D2_Walking visitor')
    if walker:
        points=[]
        for i in range(45):
            u=(i%15)/15;v=(i//15)/3
            points.append(at((1255+u*430,608+u*170-v*18)))
        instances(scene,batch.collection(GROUP),'Hall roof diners',walker,points,
                  [(0,0,i*2.1)for i in range(len(points))])
    # Tables/chairs occupy the source-visible terrace; individual positions
    # reconstruct use and density rather than exact furniture layouts.
    for pixel in [(1252,598),(1290,613),(1330,629),(1370,645),(1435,658),(1488,692),(1528,706),(1608,739),(1650,758),(1550,652),(1610,674),(1670,693)]:
        c=at(pixel)
        batch.cylinder('Hall terrace dining','metal',c,(c.x,c.y,c.z+.72),.07,sides=8)
        batch.cylinder('Hall terrace dining','white',(c.x,c.y,c.z+.72),(c.x,c.y,c.z+.8),.7,sides=12)
        for theta in [0,math.pi/2,math.pi,3*math.pi/2]:
            x=c.x+1.1*math.cos(theta);y=c.y+1.1*math.sin(theta)
            batch.box('Hall terrace dining','metal',(x,y,c.z+.45),(.45,.45,.10),theta)
            batch.box('Hall terrace dining','metal',(x+.22*math.cos(theta),y+.22*math.sin(theta),c.z+.72),(.08,.45,.60),theta)


def _d_shape(center_x, center_y, left_extent=30.0, straight_depth=14.0,
             radius=14.0, segments=24):
    """A broad D-shaped river-facing plan matching the CF source silhouette."""
    left = center_x - left_extent
    right = center_x + radius
    bottom = center_y - straight_depth
    arc_center_y = center_y
    points = [(left, bottom), (right, bottom)]
    for index in range(segments + 1):
        theta = -math.pi / 2 + math.pi * index / segments
        points.append((right + radius * math.cos(theta),
                       arc_center_y + radius * math.sin(theta)))
    points.extend([(left, center_y + radius), (left, center_y)])
    if _area(points) < 0:
        points.reverse()
    return points


def _rounded_restaurant(batch, scene, spec, materials):
    anchor = spec['anchors']['cf_scoreboard_top']
    footprint = _d_shape(float(anchor[0]), float(anchor[1]) - 8.0)
    _facade(batch, 'Centerfield rounded restaurant', footprint, 8, 19.1,
            2.2, window_material='glass_lit', pier_material='brick_light',
            window_fraction=0.76, level_height=3.7,
            mass_material='brick_dark')
    # Overhanging dark canopy/cornice is the visual anchor beneath the CF
    # board in all three source perspectives.
    _roof_and_parapet(batch, 'Centerfield rounded restaurant', footprint,
                      19.1, 'roof', 0.60, overhang=0.70)
    terrace = _inset(footprint, 0.76)
    batch.prism('Centerfield rounded restaurant', 'stone', terrace,
                19.32, 19.50)
    _roof_terrace(batch, 'Centerfield rounded restaurant', footprint, 19.52,
                  0.78, 'paving')
    for index in range(len(terrace)):
        a, b, _tangent, outward, length, angle = _edge(terrace, index)
        center = (a + b) * 0.5 + outward * 0.18
        center.z = 20.25
        batch.box('Centerfield rounded restaurant', 'metal', tuple(center),
                  (length, 0.10, 1.05), angle)
    # Sparse, source-scale rooftop furniture; the furniture stays confined to
    # the terrace so this module does not take ownership of the park.
    cx, cy = float(anchor[0]), float(anchor[1]) - 8.0
    for dx, dy in [(-16, -3), (-8, 3), (2, -2), (10, 4), (16, -1)]:
        batch.cylinder('Centerfield restaurant furniture', 'metal',
                       (cx + dx, cy + dy, 19.58),
                       (cx + dx, cy + dy, 20.15), 0.09, sides=8)
        batch.cylinder('Centerfield restaurant furniture', 'white',
                       (cx + dx, cy + dy, 20.15),
                       (cx + dx, cy + dy, 20.25), 0.72, sides=12)
    a, b, tangent, outward, length, angle = _edge(footprint, 0)
    sign_center = a.lerp(b, 0.56) + outward * 0.30
    sign_center.z = 18.35
    text(scene, batch.collection(GROUP), 'Centerfield restaurant label',
         'THE RAILYARDS', tuple(sign_center), 1.18,
         materials['screen_ink'], (math.pi / 2, 0, angle))
    return {
        'anchor': [float(anchor[0]), float(anchor[1]) - 8.0],
        'footprint': footprint,
        'base_z': 8,
        'front_roof_z': 19.1,
        'terrace_z': 20.25
    }


def build_adjacent_buildings(scene, spec, batch, materials):
    """Add the four adjacent building replacements to ``batch``.

    The returned dictionary is intentionally serializable and mirrors the
    standalone JSON spec so an integrating build can record the exact source
    regions and inferred dimensions used for this pass.
    """
    build_medical(batch, scene, spec, materials)
    wing_pixels=[(1436,395),(1609,449),(1680,405),(1538,369),(1570,344),(1525,328)]
    wing=[source_to_plane(scene,bpy.data.objects['R2_north'],p,(1944,1294),30.3)[:2] for p in wing_pixels]
    if _area(wing)<0:wing.reverse()
    _facade(batch,'Medical wing',wing,8,30.3,3.2,window_material='glass_dim',
            pier_material='brick_dark',mass_material='brick_dark',window_fraction=.30,
            level_height=5.5,window_height_fraction=.34)
    _roof_and_parapet(batch,'Medical wing',wing,30.3)
    _roof_terrace(batch,'Medical wing',wing,30.3,.91)
    _left_field_pavilion(batch, scene, spec)
    _north_entertainment_hall(batch, scene, spec)
    rounded = build_restaurant(batch, scene, spec, materials)
    result = dict(ADJACENT_SPEC)
    result['generated'] = {'group': GROUP, 'rounded_restaurant': rounded}
    return result
